#!/bin/bash
#SBATCH -J mutrate_est
#SBATCH -p all
#SBATCH -N 1
#SBATCH -n 4
#SBATCH --mem=1G
#SBATCH -t 0
#SBATCH -o oe/%x-%j.log 
#SBATCH -e oe/%x-%j.err
python cell_number_and_sample_tumor.py -f r=0.5_a=0.6_s=0.2_u=0.001_9.pkl.gz